osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - clang-3.8
    - graphicsmagick
    - rpm
    - bsdtar
install:
- clang --version
- nvm install 8
- npm prune
- npm install
script:
- npm test
- npm run dist
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
